Repository nexgeniusupc/plantguard-mobile, pull requests merged in 2023-11, with the labels that each got.

#1 feat: added home view
  lib/app.dart
  lib/views/app_card.dart
  lib/views/home_view.dart
Labels: enhancement

#2 feat: added initial auth logic and views
  assets/plantguard-logo.svg
  lib/app.dart
  lib/main.dart
  lib/models/auth/user.dart
  lib/models/auth/user.g.dart
  lib/services/auth/auth_service.dart
  lib/services/auth/user_service.dart
  lib/services/http/api_client.dart
  lib/services/http/authenticated_client.dart
  lib/services/http/http_headers.dart
  lib/services/http/media_types.dart
  lib/services/http/user_agent_client.dart
  lib/views/auth/login_view.dart
  lib/views/auth/register_view.dart
  lib/views/auth/unauthenticated_view.dart
  lib/views/home_view.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, scope: auth

#3 feat: added plant details view
  lib/views/card_details.dart
  lib/views/home_view.dart
  lib/views/plant_details_view.dart
Labels: enhancement

#4 refactor: dependency injection with providers
  lib/app.dart
  lib/main.dart
  lib/services/auth/auth_service.dart
  lib/views/auth/login_view.dart
  lib/views/auth/register_view.dart
  lib/views/auth/unauthenticated_view.dart
  lib/views/home_view.dart
  pubspec.lock
  pubspec.yaml
Labels: refactor

#5 feat: device pairing UI
  analysis_options.yaml
  lib/main.dart
  lib/models/device/device.dart
  lib/models/device/device.g.dart
  lib/models/device/pairing.dart
  lib/models/device/pairing.g.dart
  lib/services/http/api_client.dart
  lib/services/pairing/pairing_service.dart
  lib/views/home_view.dart
  lib/views/pairing/add_device_view.dart
  lib/views/pairing/confirm_device_view.dart
Labels: enhancement

#6 chore: bump to Flutter 3.16.0
  devtools_options.yaml
  pubspec.lock
Labels: chore

#7 feat: fixup styling and make views responsive
  lib/app.dart
  lib/views/app_card.dart
  lib/views/auth/login_view.dart
  lib/views/card_details.dart
  lib/views/details/plant_details_card.dart
  lib/views/details/plant_details_view.dart
  lib/views/home/home_card.dart
  lib/views/home/home_view.dart
  lib/views/home_view.dart
  lib/views/pairing/confirm_device_view.dart
  lib/views/plant_details_view.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#8 feat: added real device connection and info
  lib/main.dart
  lib/models/device/device.dart
  lib/models/device/device.g.dart
  lib/services/auth/user_service.dart
  lib/services/auth/users_service.dart
  lib/services/devices/devices_service.dart
  lib/views/details/plant_details_view.dart
  lib/views/home/home_view.dart
Labels: enhancement
